version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build:  
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_DSN=postgresql://analytics_user:analytics_pass@postgres:5432/analytics
    ports:
      - "8000:8000"

volumes:
  pgdata: {}